### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by shasderias** [leeoniya/domvm#84]
Running into an error I'm not quite sure how to debug. See following jsfiddle.

https://jsfiddle.net/tscgza0z/3/

Click alpha, then beta, etc. Eventually I'll get the following error: 
  "view.js:302 Uncaught TypeError: Cannot read property 'parentNode' of null".

Sometimes I'll also get 
  "view.js:695 Uncaught TypeError: Cannot read property 'length' of null".

The error comes and goes based on the JSONML returned by AView. For example, the following AView will work:

```
function AView(vm, a) {
  return function() {
    return ["h3", "hi"];
  };
};
```

Not sure if I'm doing something wrong or if its a bug in domvm. Any guidance would be appreciated.

Environment:
Google Chrome: 51.0.2704.84 (Official Build) m (64-bit)
domvm: 1.2.5, 1.2.6

**Comment by leeoniya** [comment]
@shasderias thanks for the report!

this looks like a bug in domvm, but i'm not yet sure what's going on. i'll dig into this today.

**Comment by shasderias** [comment]
@leeoniya thanks very much!

Happy to help where I can, but I am very much out of my depth here.

I've been poking at it the entire afternoon, here are two jsfiddles that might help you narrow down the bug:

https://jsfiddle.net/ay5LtfeL/ (note line 6, and line 32)

https://jsfiddle.net/b47ue3gz/ (identical to the previous jsfiddle, except for the deletion of line 32)

Initially, I thought the bug was triggered by invalid JSONML (first child should not be a string or a function to avoid ambiguity), but even after cleaning up any potential source of ambiguity, the bug still occurs.

Would be grateful if you could let me know if I am doing anything unidiomatic or wonky in my code as well.

Thank you for the library!

**Comment by leeoniya** [comment]
@shasderias 

So step one is to reduce this to a minimal testcase that still triggers the bug (i will be adding this to the official tests once the cause is found). The router can be removed completely and we can turn whatever we need into globals. So far this is where i'm at, but perhaps it can be stripped down even further.

```js
var state = 1;

var vmA		= domvm.view(AView, {});
var vmB		= domvm.view(BView, {});
var vAlpha	= domvm.view(AlphaView, {});
var vBeta	= domvm.view(BetaView, {});

var vApp = domvm.view(AppView, {});

vApp.mount(document.body);

setTimeout(function() {
	state = 2;
	vApp.redraw();
}, 1000);

setTimeout(function() {
	state = 1;
	vApp.redraw();
}, 2000);

// -----------------------

function AView(vm) {
	return function() {
		return ["section#a", "test"];
	};
}

function BView(vm) {
	return function() {
		return ["h3", "hiB"];
	};
};

function AlphaView(vm) {
	return function() {
		return [".alpha",
			vmA,
			vmB,
		];
	};
}

function BetaView(vm) {
	return function() {
		return [".beta", "beta.a.vm"];
	};
}

function AppView(vm) {
	return function() {
		return [".app", state == 1 ? vAlpha : vBeta];
	};
};
```

**Comment by leeoniya** [comment]
It would also be useful to see if this is a bug that was introduced in a recent version or one that has always existed. For instance, there were some significant internal changes between v1.2.3 and v1.2.5.

**Comment by leeoniya** [comment]
...AView & BetaView can be replaced by just their templates

```js
var state = 1;

var vmB		= domvm.view(BView, {});
var vAlpha	= domvm.view(AlphaView, {});

var vApp = domvm.view(AppView, {});

vApp.mount(document.body);

setTimeout(function() {
	state = 2;
	vApp.redraw();
}, 1000);

setTimeout(function() {
	state = 1;
	vApp.redraw();
}, 2000);


function BView(vm) {
	return function() {
		return ["h3", "hiB"];
	};
};

function AlphaView(vm) {
	return function() {
		return [".alpha",
			["section#a", "test"],
			vmB,
		];
	};
}

function AppView(vm) {
	return function() {
		return [".app", state == 1 ? vAlpha : [".beta", "beta.a.vm"]];
	};
};
```

**Comment by shasderias** [comment]
domvm 1.2.3 fails with an even simpler test case

https://jsfiddle.net/8e72qd23/

```
var vmA = domvm.view(AView, {});
var vApp = domvm.view(AppView, {});

vApp.mount(document.body);

function AView(vm) {
  return function() {
    return ["h3", "AView"];
  };
}

function AppView(vm) {
  return function() {
    return ["#app", [vmA]]; // works
    // return ["#app", vmA]; // 1.2.3: Uncaught TypeError: q.render.call is not a function, 1.2.5: works
  };
};
```

**Comment by leeoniya** [comment]
yeah 1.2.4 fixed that bug (where a first-child vm would be mistaken for a `props` object), but 1.2.4 also introduced a serious regression, so don't use it. when it's not a first-child, that fiddle does work in 1.2.3: https://jsfiddle.net/8e72qd23/4/

**Comment by leeoniya** [comment]
you could apply just that patch [1] to 1.2.3 and see if this bug still exists in the patched version. sorry on phone now.

[1] https://github.com/leeoniya/domvm/commit/04ac81eb14ec46c4c5612d497ec0876bcd738da2

**Comment by leeoniya** [comment]
created branch https://github.com/leeoniya/domvm/tree/issue-84 with the couple patches and it seems everything was okay then. will start looking for regressions later tonight.

**Comment by shasderias** [comment]
using branch issue-84, works like a charm

**Comment by leeoniya** [comment]
@shasderias 

This should now be fixed on 1.x-dev. The original seems to work okay. Can you please verify that the issue is fixed? Also, I could not replicate the following which you reported:

> Sometimes I'll also get "view.js:695 Uncaught TypeError: Cannot read property 'length' of null".

Is this still happening after the fix?

As a side-note, I've temporarily disabled the `replacement of a view's root node` test which fails after this patch. I think this situation is rather uncommon and a fix will need more work due to how object pooling works (since 1.2.4).

**Comment by shasderias** [comment]
Branch 1.x-dev works fine in my app. 

IIRC the second error only comes up when you continue to call vm.redraw after "Cannot read property 'parentNode' of null" occurs. i.e. if you continue to issue vm.redraw calls after domvm's internals are in a corrupt/inconsistent state. Should be a case of GIGO. Should have made it clear in my original bug report, apologies for the confusion.

Thank you for the speedy response, much appreciated.

**Comment by leeoniya** [comment]
@shasderias 

i've tagged v1.2.7 which contains this fix. thanks for reporting and providing a test case :)

**Comment by leeoniya** [comment]
`root node replacement` regression is fixed by 0b07622950a8fc5ea8720fcae3264bbd5690a956 on 1.x-dev; will be in 1.2.8
